"""multi-tenancy organizations and tenant scoping

Revision ID: 2d6765a1b770
Revises: cd540f3ad17c
Create Date: 2026-09-02 17:56:36.560332

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '2d6765a1b770'
down_revision: str | None = 'cd540f3ad17c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Deterministic development tenant for pre-multi-tenancy data (Step 8:
#: never silently attribute existing rows to an arbitrary *real* org).
DEV_CLERK_ORG_ID = "org_dev_default"
DEV_ORG_NAME = "Development (pre-multi-tenancy data)"


def _dev_organization_exists(conn: sa.Connection) -> bool:
    result = conn.execute(
        sa.text(
            "SELECT 1 FROM organizations WHERE clerk_organization_id = :clerk_id"
        ),
        {"clerk_id": DEV_CLERK_ORG_ID},
    )
    return result.first() is not None


def _insert_dev_organization(conn: sa.Connection) -> None:
    conn.execute(
        sa.text(
            "INSERT INTO organizations (id, clerk_organization_id, name, description)"
            " VALUES (gen_random_uuid(), :clerk_id, :name, :description)"
        ),
        {
            "clerk_id": DEV_CLERK_ORG_ID,
            "name": DEV_ORG_NAME,
            "description": (
                "Deterministic development tenant: all rows created before "
                "multi-tenancy (Phase 14) were assigned here by migration "
                "2d6765a1b770. Local/demo data only."
            ),
        },
    )


def _backfill_applications(conn: sa.Connection) -> None:
    statement = "UPDATE applications SET organization_id = (SELECT id FROM organizations WHERE clerk_organization_id = :clerk_id) WHERE organization_id IS NULL"
    conn.execute(sa.text(statement), {"clerk_id": DEV_CLERK_ORG_ID})


def _backfill_datasets(conn: sa.Connection) -> None:
    statement = "UPDATE datasets SET organization_id = (SELECT id FROM organizations WHERE clerk_organization_id = :clerk_id) WHERE organization_id IS NULL"
    conn.execute(sa.text(statement), {"clerk_id": DEV_CLERK_ORG_ID})


def _backfill_evaluation_runs(conn: sa.Connection) -> None:
    statement = "UPDATE evaluation_runs SET organization_id = (SELECT id FROM organizations WHERE clerk_organization_id = :clerk_id) WHERE organization_id IS NULL"
    conn.execute(sa.text(statement), {"clerk_id": DEV_CLERK_ORG_ID})


def _backfill_regression_comparisons(conn: sa.Connection) -> None:
    statement = "UPDATE regression_comparisons SET organization_id = (SELECT id FROM organizations WHERE clerk_organization_id = :clerk_id) WHERE organization_id IS NULL"
    conn.execute(sa.text(statement), {"clerk_id": DEV_CLERK_ORG_ID})


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('clerk_organization_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by_clerk_user_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_organization_id', name='uq_organization_clerk_id')
    )
    op.create_index(op.f('ix_organizations_clerk_organization_id'), 'organizations', ['clerk_organization_id'], unique=False)
    op.create_table('organization_membership_audit',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_membership_audit_organization_id'), 'organization_membership_audit', ['organization_id'], unique=False)

    # Alembic autogenerate flagged this constraint as drifted (the live
    # DB has it; the models do not). Drop it so the schema converges; the
    # downgrade restores it.
    op.drop_constraint('uq_case_result_run_testcase', 'evaluation_case_results', type_='unique')

    # Add organization_id as NULLABLE first (tables may hold data), then
    # backfill, then enforce NOT NULL + FK + index. Order matters: the
    # dev tenant must exist before any column is populated.
    op.add_column('applications', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.add_column('datasets', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.add_column('evaluation_runs', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.add_column('regression_comparisons', sa.Column('organization_id', sa.Uuid(), nullable=True))

    conn = op.get_bind()
    if not _dev_organization_exists(conn):
        _insert_dev_organization(conn)
    _backfill_applications(conn)
    _backfill_datasets(conn)
    _backfill_evaluation_runs(conn)
    _backfill_regression_comparisons(conn)

    op.alter_column('applications', 'organization_id', nullable=False)
    op.alter_column('datasets', 'organization_id', nullable=False)
    op.alter_column('evaluation_runs', 'organization_id', nullable=False)
    op.alter_column('regression_comparisons', 'organization_id', nullable=False)

    op.create_index(op.f('ix_applications_organization_id'), 'applications', ['organization_id'], unique=False)
    op.create_foreign_key('fk_applications_organization', 'applications', 'organizations', ['organization_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_datasets_organization_id'), 'datasets', ['organization_id'], unique=False)
    op.create_foreign_key('fk_datasets_organization', 'datasets', 'organizations', ['organization_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_evaluation_runs_organization_id'), 'evaluation_runs', ['organization_id'], unique=False)
    op.create_foreign_key('fk_evaluation_runs_organization', 'evaluation_runs', 'organizations', ['organization_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_regression_comparisons_created_at'), table_name='regression_comparisons')
    op.create_index(op.f('ix_regression_comparisons_organization_id'), 'regression_comparisons', ['organization_id'], unique=False)
    op.create_foreign_key('fk_regression_comparisons_organization', 'regression_comparisons', 'organizations', ['organization_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_regression_comparisons_organization', 'regression_comparisons', type_='foreignkey')
    op.drop_index(op.f('ix_regression_comparisons_organization_id'), table_name='regression_comparisons')
    op.create_index(op.f('ix_regression_comparisons_created_at'), 'regression_comparisons', ['created_at'], unique=False)
    op.drop_column('regression_comparisons', 'organization_id')
    op.drop_constraint('fk_evaluation_runs_organization', 'evaluation_runs', type_='foreignkey')
    op.drop_index(op.f('ix_evaluation_runs_organization_id'), table_name='evaluation_runs')
    op.drop_column('evaluation_runs', 'organization_id')
    op.create_unique_constraint(op.f('uq_case_result_run_testcase'), 'evaluation_case_results', ['evaluation_run_id', 'test_case_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('fk_datasets_organization', 'datasets', type_='foreignkey')
    op.drop_index(op.f('ix_datasets_organization_id'), table_name='datasets')
    op.drop_column('datasets', 'organization_id')
    op.drop_constraint('fk_applications_organization', 'applications', type_='foreignkey')
    op.drop_index(op.f('ix_applications_organization_id'), table_name='applications')
    op.drop_column('applications', 'organization_id')
    op.drop_index(op.f('ix_organization_membership_audit_organization_id'), table_name='organization_membership_audit')
    op.drop_table('organization_membership_audit')
    op.drop_index(op.f('ix_organizations_clerk_organization_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
